# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81f9d96a2f6eac1b9c5f911762ee0e0e75b65f6b5cb284bdb66dd8004cfcae2cba7d71537d8785c7df9071e56418ee64b333dbe38bfd8a6b9194e62549b0023d

test:
  secret_key_base: 723d6da58a5ae9883cb2e5d9a061899fd379b9f17cdb6a60484acf6e3f121d834801601aaa09572e0a121d9410c76375bb0a7e1fc24932f0b0d791e64d0a5434

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
